package io.github.aferdiana.myrecyclerview;

import java.util.ArrayList;

public class DataDiscography {
    public static String[][] data = new String[][]{
            {"Queen", "Released: 13 July 1973\nLabel: EMI (#EMC 3006)", "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Queen_Queen.png/220px-Queen_Queen.png","UK: Gold\nUS: Gold","Queen is the debut studio album by the British rock band Queen, released on 13 July 1973 by EMI Records in the UK and by Elektra Records in the US. It was recorded at Trident Studios and De Lane Lea Music Centre, London, with production by Roy Thomas Baker, John Anthony and the band members themselves.","1. Keep Yourself Alive\n2. Doing All Right\n3. Great King Rat\n4. My Fairy King\n5. Liar\n6. The Night Comes Down\n7. Modern Times Rock 'n' Roll\n8. Son And Daughter\n9. Jesus\n10. Seven Seas of Rhye"},
        {"Queen II", "Released: 8 March 1974\nLabel: EMI (#EMA 767)", "https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Queen_II_%28album_cover%29.jpg/220px-Queen_II_%28album_cover%29.jpg","UK: Gold","Queen II is the second studio album by the British rock band Queen. It was released on 8 March 1974 by EMI Records at midnight in the UK and by Elektra Records in the US. It was recorded at Trident Studios and Langham 1 Studios, London, in August 1973 with co-producers Roy Thomas Baker and Robin Geoffrey Cable, and engineered by Mike Stone.","1. Procession\n2. Father To Son\n3. White Queen\n4. Someday One Day\n5. The Loser In The End\n6. Ogre Battle\n7. The Fairy Fellers Masterstroke\n8. Nevermore\n9. The March Of The Black Queen\n10. Funny How Love Is\n11. Seven Seas Of Rhye"},
        {"Sheer Heart Attack", "Released: 8 November 1974\nLabel: EMI (#EMC 3061)", "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Queen_Sheer_Heart_Attack.png/220px-Queen_Sheer_Heart_Attack.png","UK: Platinum\nNL: Platinum\nUS: Gold\nRIAJ: Gold","Sheer Heart Attack is the third studio album by the British rock band Queen, released on 8 November 1974 by EMI Records in the United Kingdom and by Elektra Records in the United States. Digressing from the progressive themes featured on their first two albums, this album featured more pop-centric and conventional rock tracks and marked a step towards the 'classic' Queen sound. It was produced by the band and Roy Thomas Baker and launched Queen to mainstream popularity in the UK and throughout the world.","1. Brighton Rock\n2. Killer Queen\n3. Tenement Funster\n4. Flick Of The Wrist\n5. Lily Of The Valley\n6. Now I'm Here\n7. In The Lap Of The Gods\n8. Stone Cold Crazy\n9. Dear Friends\n10. Misfire\n11. Bring Back That Leroy Brown\n12. She Makes Me\n13. In The Lap Of The Gods ... Revisited"},
        {"A Night at the Opera", "Released: 21 November 1975\nLabel: EMI (#EMTC 103)", "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Queen_A_Night_At_The_Opera.png/220px-Queen_A_Night_At_The_Opera.png","UK: Platinum\nGER: Platinum\nAUT: Gold\nUS: 3x Platinum","A Night at the Opera is the fourth studio album by the British rock band Queen, released on 21 November 1975 by EMI Records in the United Kingdom and by Elektra Records in the United States. Produced by Roy Thomas Baker and Queen, it was reportedly the most expensive album ever recorded at the time of its release. The album's title is taken from the Marx Brothers film of the same name.","1. Death On Two Legs (Dedicated To ...)\n2. Lazing On A Sundy Afternoon\n3. I'm In Love With My Car\n4. You're My Best Friend\n5. '39\n6. Sweet Lady\n7. Seaside Rendezvous\n8. The Prophet's Song\n9. Love Of My Life\n10. Good Company\n11. Bohemian Rhapsody\n12. God Save The Queen"},
        {"A Day at the Races", "Released: 10 December 1976\nLabel: EMI (#EMTC 104)", "https://upload.wikimedia.org/wikipedia/en/thumb/3/31/A_Day_at_the_Races_%28Queen%29.jpg/220px-A_Day_at_the_Races_%28Queen%29.jpg","UK: Gold\nNL: Gold\nUS: Platinum","A Day at the Races is the fifth studio album by the British rock band Queen, released on 10 December 1976 by EMI Records in the United Kingdom and by Elektra Records in the United States. It was the band's first completely self-produced album, and the first not to feature producer Roy Thomas Baker. Recorded at Sarm East, The Manor and Wessex Studios in England, A Day at the Races was engineered by Mike Stone. The album serves as a companion album to the band's previous album, A Night at the Opera, both taking their names from Marx Brothers films, as well as sharing similar packaging and eclectic musical themes.","1. Tie Your Mother Down\n2. You Take My Breath Away\n3. Long Away\n4. The Millionaire Waltz\n5. You And I\n6. Somebody To Love\n7. White Man\n8. Good Old Fashioned Lover Boy\n9. Drowse\n10. Teo Torriatte (Let Us Cling Together)"},
        {"News of the World", "Released: 28 October 1977\nLabel: EMI (#EMA 784)", "https://upload.wikimedia.org/wikipedia/en/thumb/e/ea/Queen_News_Of_The_World.png/220px-Queen_News_Of_The_World.png","UK: Gold\nGER: Platinum\nNL: Platinum\nUS: 4x Platinum\nSNEP: Gold","News of the World is the sixth studio album by the British rock band Queen, released on 28 October 1977 by EMI Records in the United Kingdom and by Elektra Records in the United States. News of the World was the band's second album to be recorded at Sarm West and Wessex Studios, London, and engineered by Mike Stone, and was co-produced by the band and Stone. Recording took place at the same time the Sex Pistols were busy recording Never Mind the Bollocks, Here's the Sex Pistols, which led to several meetings between band members.","1. We Will Rock You\n2. We Are the Champions\n3. Sheer Heart Attack\n4. All Dead, All Dead\n5. Spread Your Wings\n6. Fight From The Inside\n7. Get Down, Make Love\n8. Sleeping on the Sidewalk\n9. Who Needs You\n10. It's Late\n11. My Melancholy Blues"},
        {"Jazz", "Released: 10 November 1978\nLabel: EMI (#EMA 788)", "https://upload.wikimedia.org/wikipedia/en/thumb/0/06/Queen_Jazz.png/220px-Queen_Jazz.png","UK: Gold\nGER: Gold\nAUT: Gold\nNL: Platinum\nUS: Platinum\nFRA: Gold","Jazz is the seventh studio album by the British rock band Queen. It was released on 10 November 1978 by EMI Records in the United Kingdom and by Elektra Records in the United States. Produced by Roy Thomas Baker, the album artwork was suggested by Roger Taylor, who previously saw a similar design painted on the Berlin Wall. The album's varying musical styles were alternately praised and criticised. It reached number two in the UK Albums Chart and number six on the US Billboard 200. Jazz has sold over five million copies worldwide.","1. Mustapha\n2. Fat Bottomed Girls\n3. Jealousy\n4. Bicycle Race\n5. If You Can't Beat Them\n6. Let Me Entertain You\n7. Dead On Time\n8. In Only Seven Days\n9. Dreamers Ball\n10. Fun It\n11. Leaving Home Ain't Easy\n12. Don't Stop Me Now\n13. More Of That Jazz"},
        {"The Game", "Released: 27 June 1980\nLabel: EMI (#EMA 795)", "https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Queen_The_Game.png/220px-Queen_The_Game.png","UK: Gold\nGER: Gold\nAUT: Gold\nNL: Gold\nUS: 4x Platinum","The Game is the eighth studio album by the British rock band Queen. It was released on 30 June 1980 by EMI Records in the UK and by Elektra Records in the US. The Game features a different sound from its predecessor, Jazz (1978). The Game was the first Queen album to use a synthesizer[4] (an Oberheim OB-X). 'Crazy Little Thing Called Love', 'Sail Away Sweet Sister', 'Coming Soon' and 'Save Me' were recorded from June to July 1979. The remaining songs were recorded between February and May 1980.","1. Play The Game\n2. Dragon Attack\n3. Another One Bites the Dust\n4. Need Your Loving Tonight\n5. Crazy Little Thing Called Love\n6. Rock It (Prime Jive)\n7. Don't Try Suicide\n8. Sail Away Sweet Sister\n9. Coming Soon\n10. Save Me"},
        {"Flash Gordon", "Released: 8 December 1980\nLabel: EMI (#EMC 3351)", "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Queen_Flash_Gordon.png/220px-Queen_Flash_Gordon.png","UK: Gold","Flash Gordon is the first soundtrack album by the British rock band Queen, released on 8 December 1980 by EMI Records in the UK and in February 1981 by Elektra Records in the US. It was one of two film soundtracks that they produced along with Highlander. It is the soundtrack to the science fiction film Flash Gordon, and features lyrics on only two tracks. 'Flash's Theme' was the only single to be released from the album under the title 'Flash'. The album reached number 10 on the UK charts and number 23 in the US. The album was reissued worldwide on 27 June 2011 (excluding the US and Canada, where it was released on 27 September 2011) as part of the band's 40th anniversary. The reissue adds an EP of related tracks.","1. Flash's Theme\n2. In The Space Capsule\n3. Ming's Theme\n4. The Ring\n5. Football Fight\n6. In The Death Cell\n7. Execution Of Flash\n8. The Kiss\n9. Arboria\n10. Escape From The Swamp\n11. Flash To The Rescue\n12. Vultan's Theme\n13. Battle Theme\n14. The Wedding March\n15. Marriage Of Dale And Ming\n16. Crash Dive On Mingo City\n17. Flash's Theme Reprise\n18. The Hero"},
        {"Hot Space", "Released: 21 May 1982\nLabel: EMI (#EMA 797)", "https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/Queen_Hot_Space.png/220px-Queen_Hot_Space.png","UK: Gold\nAUT: Gold\nUS: Gold","Hot Space is the tenth studio album by the British rock band Queen. It was released on 21 May 1982 by EMI Records in the UK and by Elektra Records in the US. Marking a notable shift in direction from their earlier work, they employed many elements of disco, funk, rhythm and blues, dance and pop music on the album. This made the album less popular with fans who preferred the traditional rock style they had come to associate with the band. Queen's decision to record a dance-oriented album germinated with the massive success in the US of their 1980 hit 'Another One Bites the Dust' (and to a lesser extent, the UK success of the song).","1. Staying Power\n2. Dancer\n3. Back Chat\n4. Body Language\n5. Action This Day\n6. Put Out The Fire\n7. Life Is Real (Song For Lennon)\n8. Calling All Girls\n9. Las Palabras De Amor (The Words of Love)\n10. Cool Cat\n11. Under Pressure"},
        {"The Works", "Released: 27 February 1984\nLabel: EMI (#EMC 240014)", "https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Queen_The_Works.png/220px-Queen_The_Works.png","UK: Platinum\nGER: Platinum\nAUT: Platinum\nNL: Gold\nUS: Gold","The Works is the eleventh studio album by the British rock band Queen, released on 27 February 1984 by EMI Records in the United Kingdom and it is the band's first studio album to be released by Capitol Records in the United States. After the synth-heavy Hot Space (1982), the album saw the re-emergence of Brian May and Roger Taylor's rock sound, while still incorporating the early 80s retro futuristic electronic music (Freddie Mercury) and New York funk scenes (John Deacon). Recorded at the Record Plant Studios in Los Angeles, California and Musicland Studios in Munich, Germany from August 1983 to January 1984, the album's title comes from a comment Taylor made as recording began – 'Let's give them the works!' During the decade, after a negative reaction against and ban of the music video for 'I Want to Break Free' in the United States, the band decided not to tour in North America and lost the top spot in U.S. sales, but sales around the world (especially Europe) would be even better. The Works has sold over 6 million copies worldwide.","1. Radio Ga Ga\n2. Tear It Up\n3. It's A Hard Life\n4. Man On The Prowl\n5. Machines (Back To Humans)\n6. I Want To Break Free\n7. Keep Passing The Open Windows\n8. Hammer To Fall\n9. Is This The World We Created?"},
        {"A Kind of Magic", "Released: 3 June 1986\nLabel: EMI (#EU 3509)", "https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Queen_A_Kind_Of_Magic.png/220px-Queen_A_Kind_Of_Magic.png","UK: 2× Platinum\nGER: 3× Gold\nAUT: Platinum\nUS: Gold\nFRA: Gold","A Kind of Magic is the twelfth studio album by the British rock band Queen, released on 3 June 1986 by EMI Records in the UK and by Capitol Records in the US. It was their first studio album to be recorded digitally, and is based on the soundtrack to the film Highlander, the first in a series directed by Russell Mulcahy.\n\nA Kind of Magic was Queen's first album to be released since they had been acclaimed for their performance at the 1985 Live Aid concert. It was an immediate hit in the UK, going straight to number one and selling 100,000 copies in its first week. It remained in the UK charts for 63 weeks, selling about six million copies worldwide (600,000 in the UK alone). The album spawned four hit singles: the album's title track 'A Kind of Magic', 'One Vision', 'Friends Will Be Friends', and 'Who Wants to Live Forever', which features an orchestra conducted by Michael Kamen, while the last track, 'Princes of the Universe', is the theme song to Highlander.","1. One Vision\n2. A Kind Of Magic\n3. One Year Of Love\n4. Pain Is So Close to Pleasure\n5. Friends Will Be Friends\n6. Who Wants To Live Forever\n7. Gimme The Prize (Murgans Theme)\n8. Don't Lose Your Head\n9. Princes Of The Universe"},
        {"The Miracle", "Released: 22 May 1989\nLabel: Parlophone/EMI (#PCSD 107)", "https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/Queen_The_Miracle.png/220px-Queen_The_Miracle.png","UK: Platinum\nGER: Platinum\nAUT: Gold\nNL: Platinum\nFRA: Gold","The Miracle is the thirteenth studio album by the British rock band Queen, released on 22 May 1989 by Capitol Records in the US, it is the band's first studio album to be released by Parlophone Records in the UK. The album was recorded as the band recovered from Brian May's marital problems and Freddie Mercury's AIDS diagnosis in 1987 (which was known to the band, though not publicised at the time). Recording started in January 1988 and lasted for an entire year. The album was originally going to be called The Invisible Men, but three weeks before the release, according to Roger Taylor, they decided to change the name to The Miracle. It was also the last Queen album with a band photo on the front cover.","1. Party\n2. Khashoggis Ship\n3. The Miracle\n4. I Want It All\n5. The Invisible\n6. Breakthrou\n7. Rain Must Fall\n8. Scandal\n9. My Baby Does Me\n10. Was It All Worth It"},
        {"Innuendo", "Released: 5 February 1991\nLabel: Parlophone/EMI, Hollywood (#PCSD 115)", "https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/Queen_Innuendo.png/220px-Queen_Innuendo.png","UK: Platinum\nGER: Platinum\nAUT: Platinum\nNL: 2× Platinum\nUS: Gold\nFRA: Platinum","Innuendo is the fourteenth studio album by the British rock band Queen, released on 5 February 1991 by Parlophone in the United Kingdom and it is the band's first studio album to be released by Hollywood Records in the United States. Produced by David Richards and the band, it was the band's last album to be released in lead singer Freddie Mercury’s lifetime, and their most recent one to be composed of entirely new material. It reached the No. 1 spot on the UK album charts and stayed at that position for two weeks, and also peaked at No. 1 in Italy, the Netherlands, Germany, Switzerland, staying at No. 1 for three weeks, four weeks, six weeks, and eight weeks, respectively. It was the first Queen album to go Gold in the US upon its release since The Works in 1984.","1. Innuendo\n2. I'm Going Slightly Mad\n3. Headlong\n4. I Can't Live With You\n5. Don't Try So Hard\n6. Ride The Wild Wind\n7. All God's People\n8. These Are The Days Of Our Lives\n9. Delilah\n10. The Hitman\n11. Bijou\n12. The Show Must Go On"},
        {"Made in Heaven", "Released: 6 November 1995\nLabel: Parlophone/EMI, Hollywood (#PCSD 167)", "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Madeinheaven.jpg/220px-Madeinheaven.jpg","UK: 4× Platinum\nAUS: Platinum\nGER: 3× Platinum\nAUT: 2× Platinum\nNOR: Platinum\nUS: Gold\nFRA: 2× Platinum","Made in Heaven is the fifteenth and final studio album by the British rock band Queen, released on 6 November 1995 by Parlophone Records in the United Kingdom and by Hollywood Records in the United States. It was the band's first release after the death of lead singer Freddie Mercury in 1991. Following Mercury's death, guitarist Brian May, drummer Roger Taylor, and bass guitarist John Deacon worked with vocal and piano parts that Mercury recorded before his death, adding new instrumentation to the recordings. Both stages of recording, before and after Mercury's death, were completed at the band's studio in Montreux, Switzerland. The album debuted at number 1 in the UK where it went 5× platinum. The album has sold around 20 million copies around the world.","1. It's A Beautiful Day\n2. Made In Heaven\n3. Let Me Live\n4. Mother Love\n5. My Life Has Been Saved\n6. I Was Born To Love You\n7. Heaven For Everyone\n8. Too Much Love Will Kill You\n9. You Don't Fool Me\n10. A Winter's Tale\n11. It's A Beautiful Day (Reprise)"}
    };

    public static ArrayList<QueenDiscography> getListData() {
        QueenDiscography queenDiscography = null;
        ArrayList<QueenDiscography> list = new ArrayList<>();
        for (String[] aData : data) {
            queenDiscography = new QueenDiscography();
            queenDiscography.setTitle(aData[0]);
            queenDiscography.setAlbumDetail(aData[1]);
            queenDiscography.setCover(aData[2]);
            queenDiscography.setCertification(aData[3]);
            queenDiscography.setStory(aData[4]);
            queenDiscography.setSong(aData[5]);

            list.add(queenDiscography);
        }
        return list;
    }
}
